sudo: false
language: java
jdk: oraclejdk7

env:
- JAVA_OPTS="-Xmx1024m -Xms1024m"

install:
- ./acceptance-test/setup-local-ssh.sh


script:
- ./gradlew check


after_success:
- test ${TRAVIS_TAG} && ./gradlew bintrayUpload
